# Generated by Django 5.0.7 on 2024-07-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_questions_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answered_question_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='correct_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='correct_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='incorrect_num',
            field=models.IntegerField(default=0),
        ),
    ]
