# Generated by Django 5.0.7 on 2024-07-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_answered_question_num_user_correct_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_correct_rate',
            field=models.IntegerField(default=0),
        ),
    ]
